{
 "title": "first",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "floor",
    "query": {
     "query": "label_values(coffee_cups_total,floor)"
    }
   },
   {
    "name": "user",
    "query": {
     "query": "label_values(coffee_cups_total,user)"
    }
   },
   {
    "name": "decaf",
    "query": {
     "query": "label_values(coffee_cups_total,decaf)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Coffee Temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "coffee_temp_celsius{floor=\"$floor\", user=\"$user\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Brain",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "brain_cpu_usage_percent{floor=\"$floor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Coffe Cups (filtered)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "coffee_cups_total{decaf=\"$decaf\", floor=\"$floor\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}